[package]
name = "Examples"
version = "0.0.0"

[addresses]
hello_blockchain = "_"

[dependencies]
AptosFramework = { git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'aptos-framework-v1.2.0',subdir = 'aptos-move/framework/aptos-framework' }
